# Generated by Django 4.0.1 on 2022-02-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craigshop', '0004_order_datetime_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_addr',
            field=models.TextField(default=''),
        ),
    ]
